### ISSUE TITLE
HBCI Payment authorization wrong screens

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#1163]
Currently, the backend sends wrong redirect URLs for HBCI payment authorization. User sees consent screens instead of screens with payments because redirection is done to AIS module, not to PIS

**Comment by electronicpeter** [comment]
I cant find redirection code. Flowable engine for HBCI Payment starts with 


/**
 * Initiates Account list consent. Forcefully redirects user to consent initiation screen.
 */
@Slf4j
@Service("hbciAskForPsuId")
@RequiredArgsConstructor
public class HbciAisConsentService extends ValidatedExecution<HbciContext> {

    @Override
    protected void doRealExecution(DelegateExecution execution, HbciContext context) {
        ContextUtil.getAndUpdateContext(execution, (HbciContext ctx) -> ctx.setViolations(ImmutableSet.of()));
    }


As can be seen this class is AIS. There is no corresponding PIS class. I think this was done by purpose, because authentication is indepent of pis and ais.
However, after authentication is done, user is redirected to PIS urls, as designed.

**Comment by valb3r** [comment]
Fixed by
https://github.com/adorsys/open-banking-gateway/pull/1164
