### ISSUE TITLE
Create a banking protocol facade (java class) that give a call for each services (List account and List transaction)

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/open-banking-gateway#133]
This should be done incrementally

**Comment by francis-pouatcha** [comment]
We need a synchronization on how we are intending to setup the BankingProtocolFacade. WE will hae to deal with following topics:
1- The dependency management. In order to keep Facade and Implementation decoupled at compile time, we can still define a banking-protocol-facade sub project. This can contain the interface and all VO needed by the BankingProtocol implementations.
2- The approach for defining the Facade. I can take a use case based approach, setting up a Project and defining all method i need for the defined use cases. Then we see how to proceed.

What do you thing about this approach?

**Comment by valb3r** [comment]
Done with #194 merged tasks
