### ISSUE TITLE
FintechUI Back to select Bank

### ISSUE THREAD

**Issue by electronicpeter** [adorsys/open-banking-gateway#405]
In the Fintech-UI a possibilty must be created to get back to bank-selection page.

**Comment by rjtch** [comment]
i always get this warning from google-chrome so that i can't logout anymore if i don't manually delete the cookies.
"A cookie associated with a resource at http://localhost/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032. "
